<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="6" hostname="PC-BSAphoto" failures="1" tests="1" name="SampleTestSearch" time="1.655" errors="0" timestamp="09 Mar 2021 18:43:24 GMT">
  <testcase classname="com.Sample.testobjects.SampleTest" name="searchItemWithResults" time="1.13">
    <failure type="java.lang.AssertionError" message="expected [pass] but found [fail]">
      <![CDATA[java.lang.AssertionError: expected [pass] but found [fail]
	at com.Sample.testobjects.SampleTest.searchItemWithResults(SampleTest.java:251)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- searchItemWithResults -->
  <testcase classname="com.Sample.testobjects.SampleTest" name="blankEmailOrNumberLogIn" time="0.0">
    <ignored/>
  </testcase> <!-- blankEmailOrNumberLogIn -->
  <testcase classname="com.Sample.testobjects.SampleTest" name="logOut" time="0.0">
    <ignored/>
  </testcase> <!-- logOut -->
  <testcase classname="com.Sample.testobjects.SampleTest" name="successfulLogIn" time="0.0">
    <ignored/>
  </testcase> <!-- successfulLogIn -->
  <testcase classname="com.Sample.testobjects.SampleTest" name="incorrectPassword" time="0.0">
    <ignored/>
  </testcase> <!-- incorrectPassword -->
  <testcase classname="com.Sample.testobjects.SampleTest" name="noAccountFound" time="0.0">
    <ignored/>
  </testcase> <!-- noAccountFound -->
  <testcase classname="com.Sample.testobjects.SampleTest" name="blankPassword" time="0.0">
    <ignored/>
  </testcase> <!-- blankPassword -->
</testsuite> <!-- SampleTestSearch -->
