<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="PC-BSAphoto" failures="2" tests="7" name="com.Shopify.testobjects.GSPRegressionSuiteTest" time="85.291" errors="0" timestamp="28 Apr 2023 07:06:25 GMT" skipped="0">
  <testcase classname="com.Shopify.testobjects.GSPRegressionSuiteTest" name="successfulLogin" time="3.542"/>
  <testcase classname="com.Shopify.testobjects.GSPRegressionSuiteTest" name="openTransMisroutedDelivery" time="0.737">
    <failure message="expected [pass] but found [fail]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [pass] but found [fail]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at com.Shopify.testobjects.GSPRegressionSuiteTest.openTransMisroutedDelivery(GSPRegressionSuiteTest.java:176)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- openTransMisroutedDelivery -->
  <testcase classname="com.Shopify.testobjects.GSPRegressionSuiteTest" name="invalidPasswordLogin" time="4.228"/>
  <testcase classname="com.Shopify.testobjects.GSPRegressionSuiteTest" name="deliveriesSearchWithResult" time="63.706">
    <failure message="expected [pass] but found [fail]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [pass] but found [fail]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at com.Shopify.testobjects.GSPRegressionSuiteTest.deliveriesSearchWithResult(GSPRegressionSuiteTest.java:160)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- deliveriesSearchWithResult -->
  <testcase classname="com.Shopify.testobjects.GSPRegressionSuiteTest" name="deliveriesSearchNoResult" time="3.178"/>
  <testcase classname="com.Shopify.testobjects.GSPRegressionSuiteTest" name="openTransNoDocumentDelivery" time="5.241"/>
  <testcase classname="com.Shopify.testobjects.GSPRegressionSuiteTest" name="openTransDeliveries" time="4.659"/>
</testsuite> <!-- com.Shopify.testobjects.GSPRegressionSuiteTest -->
